source "https://rubygems.org"

gem 'stasis'
# gem 'directory_watcher', '1.4.1'
# gem 'slop', '3.3.2'
# gem 'tilt', '1.3.3'
# gem 'albino', '>=0'
# gem 'coffee-script', '>=0'
# gem 'haml', '>=0'
# gem 'nokogiri', '>=0'
# gem 'rake', '>=0'
# gem 'rocco', '>=0'
# gem 'rspec', '~>1.0'
gem 'directory_watcher'
gem 'slop'
gem 'tilt'
gem 'albino'
gem 'coffee-script'
gem 'haml'
gem 'nokogiri'
gem 'rake'
gem 'rocco'
gem 'rspec'

gem 'sass'
gem 'redcarpet'

